#Enable multiple megas at one time
multipleMegas = false
#Enable mega evolution only for battles
battleModeOnly = false
#Allows you to have multiple primals in your team
multiplePrimals = true
#Enables/Disables zMoves in game
zMoves = true
#Enables/Disables teralization in game
teralization = true
#Enables etermax eternus forme
etermaxForme = true
#Enables/Disables dmax in game
dynamax = true
#Enables/Disables dmax in game
mega = true
#Allows you to dynamax anywhere you dont need to be near the dynamax area
dynamaxAnywhere = false
#Range around a power spot where Dynamax is allowed
# Default: 20
# Range: 0 ~ 10000
powerSpotRange = 20
#By how many times should the pokemon size increase when g/dmaxing
# Default: 4
# Range: -10 ~ 10000
dynamaxScaleFactor = 4
# Enable/Disable loading of showdown files from the mod, 
# note this means once you load the game and the showdown changes have been affected you disable
# this it will stop overwriting it ever load, this is for people who want to edit showdown 
# but can't since mega showdown keeps overriding the files
showdownFilesLoading = true
#Enable/Disable mega pokemons form reverting when battle starts
revertMegas = true
#Number of tera shards required to change tera type
# Default: 50
# Range: 1 ~ 50
teraShardRequired = 50
#Terashard drop rate
# Default: 10.0
# Range: -1.0 ~ 100.0
teraShardDropRate = 10.0
#Stellar tera drop rate
# Default: 1.0
# Range: -1.0 ~ 100.0
stellarShardDropRate = 1.0
