#Disable wool drops to force the player to get shears.
disableWoolDrops = true
#Reset all skills to 1 when a player dies.
deathSkillReset = false
#Should you gain health on set level ups?
HealthBonus = true
#Toggle the visibility of the tab buttons in the inventory.
showTabButtons = true
#Starting cost of upgrading to level 2, in experience points.
# Default: 7
# Range: 0 ~ 1000
startingCost = 10
#Global scaling multiplier for XP costs.
# Default: 1.0
# Range: 0.1 ~ 10.0
xpScalingMultiplier = 1.75
#Maximum level each skill can be upgraded to.
# Default: 32
# Range: 2 ~ 100
maximumLevel = 50
#List of substitutions to perform in names in skill lock lists.
#Useful if you're using a resource pack to change the names of skills, this config doesn't affect gameplay, just accepted values in other configs so it's easier to think about
#Format: key=value
#Valid values: attack, defense, mining, gathering, farming, building, agility, magic
#Enable or disable skill leveling via GUI or selection. If disabled, skill levels must be granted by commands.
enableSkillLeveling = true
#Enable or disable the skill level-up message.
enableSkillUpMessage = true
skillAliases = ["defense=defense"]
# Default: 0.15
# Range: 0.0 ~ 10.0
attackDamageBonus = 0.10
# Default: 0.15
# Range: 0.0 ~ 10.0
armorBonus = 0.05
# Default: 0.05
# Range: 0.0 ~ 1.0
movementSpeedBonus = 0.05
#The registry ID of the attribute to use for the Magic skill (e.g. 'modid:spell_power')
magicAttribute = "minecraft:generic.luck"
# Default: 0.05
# Range: 0.0 ~ 10.0
MagicBonus = 0.05
# Default: 0.25
# Range: 0.0 ~ 5.0
blockReachBonus = 0.25
# Default: 0.25
# Range: 0.0 ~ 5.0
miningSpeedMultiplier = 0.25
# Default: 0.25
# Range: 0.0 ~ 1.0
cropGrowthChancePer5Levels = 0.15
#Bonus XP multiplier per 5 levels of Gathering (e.g., 0.05 = +5% XP per step)
# Default: 0.05
# Range: 0.0 ~ 1.0
gatheringXpBonus = 0.01
#How many total skill levels are required for each heart gained.
# Default: 10
# Range: 1 ~ 100
levelsPerHeart = 10
#How much health (in half-hearts) is granted per configured levelsPerHeart.
# Default: 2.0
# Range: 0.5 ~ 20.0
healthPerHeart = 2.0
